@startuml
'https://plantuml.com/state-diagram

[*] --> UP : JOIN
UP --> LEFT : LEAVE
UP --> SUSPICIOUS : SUSPECT
DOWN --> SUSPICIOUS : SUSPECT
SUSPICIOUS --> UP : UPDATE/HEARTBEAT
DOWN --> UP : UPDATE/HEARTBEAT
SUSPICIOUS --> DOWN : STRONG_SUSPECT
UP --> DOWN : STRONG_SUSPECT

DOWN --> LEFT : FAIL/LEAVE

SUSPICIOUS --> LEFT : LEAVE
LEFT --> REMOVED : REMOVE

@enduml
